version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql.self_learning.local
    hostname: postgresql.self_learning.local
    restart: always
    environment:
      POSTGRES_USER: backend101
      POSTGRES_PASSWORD: backend101
      POSTGRES_DB: backend101
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local